# Generated by Django 5.0.1 on 2024-01-26 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='damaged_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ims.damageditem'),
        ),
        migrations.AddField(
            model_name='message',
            name='maintainable_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ims.maintainableitem'),
        ),
        migrations.AddField(
            model_name='message',
            name='order_takeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ims.takeoutorders'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
